### ISSUE TITLE
HashiCorp Configuration Language (HCL) Support

### ISSUE THREAD

**Issue by karras** [pygments/pygments#1353]
The HashiCorp Configuration Language (HCL) is becoming very popular these days and also very handy to have in other projects such as MediaWiki, which make use of pygments.

**Comment by karras** [comment]
Specification: https://github.com/hashicorp/hcl

@hairmare ^

**Comment by appleshampooid** [comment]
pygments does support HCL but you have to label it as `terraform` which isn't 100% accurate, but seems to work pretty well for me.

**Comment by karras** [comment]
Good catch, totally mist that one. Thanks!

**Comment by lgiordani** [comment]
Can you please have a look at #1756? Feedback is welcome. Thanks!

**Comment by lorengordon** [comment]
@lgiordani I have a block that looks like this, which is failing when using pygments 2.9.0 with `WARNING: Could not lex literal_block as "terraform". Highlighting skipped.` Strange thing is this syntax is valid with both HCL 1 and HCL 2, and it was working fine with pygments 2.8.1.

```
```terraform
provider "aws" {}

module "test-lx-instance" {
  source = "git::https://github.com/plus3it/terraform-aws-watchmaker//modules/lx-instance/"

  Name      = "tf-watchmaker-lx-autoscale"
  AmiId     = "__AMIID__"
  AmiDistro = "__AMIDISTRO__"
}
```

**Comment by lgiordani** [comment]
@lorengordon I'll have a look as soon as possible, thanks for the test case

**Comment by Anteru** [comment]
Can someone confirm this fixed by #1756? I see an error on the first `}` but that seems unrelated?

**Comment by Jeinhaus** [comment]
I am using [terragrunt](https://terragrunt.gruntwork.io/) that also uses HCL for configuration. The changes from #1756 do not fix that. Should I open another issue for this (even though it's using HCL)?

An example for terragrunt's configuration is below:
```
terraform {
  source =
    "github.com:foo/infrastructure-modules.git//app?ref=v0.0.1"
}
inputs = {
  instance_count = 10
  instance_type  = "m4.large"
}
```

**Comment by Anteru** [comment]
Given #1756 doesn't fix your issue, but is already merged, I'd suggest to open a new one. For my understanding: Is terragrunt using a dialect of HCL or is that a problem for "plain" HCL?

**Comment by lorengordon** [comment]
@Anteru The linked PR #1756 is included in the 2.9.0 release and does not appear to fix this issue. I can't test what it _does_ work for, but it does not work for basic Terraform syntax that is the same in both HCL2 and HCL1, as I mentioned [above](https://github.com/pygments/pygments/issues/1353#issuecomment-862414618).

**Comment by lgiordani** [comment]
Hi all, my work on #1756 was checked against a large Terraform code base (~100k lines), but I didn't implement the HCL specification following it rule by rule, so I'm not surprised that isn't covered. I think it's simpler to open a new issue with the failing use case and steps to reproduce so that whoever has time to look into it can easily create the test environment.

**Comment by lorengordon** [comment]
@lgiordani Just closing the loop, there's a patch for the problem I was noticing in #1987 ...

**Comment by lgiordani** [comment]
Thank you @lorengordon!

**Comment by lorengordon** [comment]
Can confirm #2097 fixed the issue for us, in the 2.12.0 release.

**Comment by lgiordani** [comment]
Thank you @lorengordon!
