### ISSUE TITLE
Moving pygments.rb to pygments organization

### ISSUE THREAD

**Issue by slonopotamus** [pygments/pygments#1660]
Hello, guys! I've started an effort to reanimate pygments.rb project (a Ruby gem that exposes pygments to Ruby programs): https://github.com/tmm1/pygments.rb/issues/197

The problem is, pygments.rb is currently a personal repo, so previous developer cannot grant me admin rights and it would be more convenient if pygments.rb belonged to an organization.

Would you accept pygments.rb into pygments GitHub organization?

**Comment by Anteru** [comment]
@birkenfeld Any objections? This would be the first family member in the Pygments organization on the path to world domination ... Personally I don't have a problem with that, and it seems like the original developer of pygments.rb doesn't object either, but it's obviously making this an "official Pygments" project now and I can't make that call by myself.

**Comment by slonopotamus** [comment]
I don't think you need to call it "official". Just "closely related". For example, if you look at [Asciidoctor organization](https://github.com/asciidoctor), you will find multiple repos maintained by different people. These repos provide different bits of functionality around Asciidoctor, but there is no "official" thing, it's just a place for users to easier find related projects and a way to overcome individual repo limitations.

**Comment by birkenfeld** [comment]
:+1:

**Comment by Anteru** [comment]
All right, we got the approval from our boss. How can we transition the repository into the organization? Do I need to press some buttons?

**Comment by slonopotamus** [comment]
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

I believe you need to temporarily grant @tmm1 permission to create repositories in pygments organization, then he makes the transfer, they you grant me/whoever permissions to manage repository.

**Comment by Anteru** [comment]
Done. @tmm1 -- can you please move Pygments.rb over here, I'll take ownership of it then and add @slonopotamus as a developer there?

**Comment by Anteru** [comment]
Wait, my bad, this is not the right approach. If you check the documentation, @tmm1 should create a transfer request, and then I can accept it. This method here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account @slonopotamus Can you please ping @tmm1 and ask him to initiate the transfer? I'll accept the transfer, but this way we don't have to mess around with invites

**Comment by slonopotamus** [comment]
I don't have any other communication channels with @tmm1 currently besides GitHub pinging, so we might need to wait a bit when he sees it. And we have already pinged him in this issue more than enough times I hope :)

@gfx, sorry for bothering you, do you have some more interactive ways to contact @tmm1?

**Comment by tmm1** [comment]
I tried to transfer but it didn't work.

>You don’t have the permission to create public repositories on pygments

**Comment by Anteru** [comment]
@tmm1 Can you please try again? I've invited you as a member here, so once you join you should be able to transfer the repository, and then I'll take over. Sorry for the inconvenience and probably dozens of GitHub ping emails :/

**Comment by tmm1** [comment]
Done!

**Comment by slonopotamus** [comment]
Woot! 🎉

**Comment by Anteru** [comment]
That was quick, thanks everyone!

**Comment by slonopotamus** [comment]
@Anteru You forgot a minor detail :D I still need repo permissions, at least to add rubygems.org secret token.

**Comment by slonopotamus** [comment]
UPD: Cofirming that I've joined Pygments organization and have permissions on pygments.rb repo.

**Comment by slonopotamus** [comment]
That's what settings are available to me:

![Screenshot_20210107-222004](https://user-images.githubusercontent.com/92637/103934759-92ecac00-5136-11eb-8b48-54d484c5d881.png)

**Comment by slonopotamus** [comment]
@Anthirian ping

**Comment by slonopotamus** [comment]
@Anteru ping

**Comment by Anteru** [comment]
I made you maintainer of that repository, but it looks like you have to be administrator to add secret tokens ... let me try pressing a few more buttons.

**Comment by slonopotamus** [comment]
Yep, now it works!

**Comment by gfx** [comment]
Great! This is now under the same org as Python Pygments 👏 👏 👏

**Comment by gfx** [comment]
Great 👏
